runtime: php80 # Specify the PHP runtime version

# Document root where your main application files are located
runtime_config:
  document_root: .

entrypoint: serve handler.php # Entry point for your application

handlers:
  # Serve static files (CSS, images, JS)
  - url: /(.+\.(gif|png|jpg|css|js|map|PNG))$
    static_files: \1
    upload: .+\.(gif|png|jpg|css|js|map|PNG)$

  # All other requests are handled by handler.php
  - url: /.*
    script: auto

env_variables:
  # Replace these with your actual database connection details
  CLOUDSQL_USER: root
  CLOUDSQL_DB: meter_box_app # Ensure this matches your Cloud SQL database name
  CLOUDSQL_PASSWORD: Lebo@2024
  CLOUDSQL_DSN: /cloudsql/tonal-premise-440712-s2:us-central1:my-khanyisa-instance
